### ISSUE TITLE
[FEATURE] Add `awsctl get vpc` command

### ISSUE THREAD

**Issue by surajnarwade** [surajincloud/awsctl#11]
### Description

This command should list the vpc

```
awsctl get vpc
```

**Comment by riteshsonawane1372** [comment]
Can you give an example output on how to frame the output.

**Comment by riteshsonawane1372** [comment]
> Can you give an example output on how to frame the output.

@surajnarwade

**Comment by surajnarwade** [comment]
ideally it should be VPC name and CIDR range to begin with
