### ISSUE TITLE
[FEATURE] common `--region` flag

### ISSUE THREAD

**Issue by surajnarwade** [surajincloud/awsctl#12]
### Description

there should be `--region` flag which should be common for all the commands. 

Similar to how `--cluster` or `--kubeconfig` flag is available in kubectl.

**Comment by riteshsonawane1372** [comment]
something like ```awsctl get ec2 --region=us-east``` ?.

**Comment by riteshsonawane1372** [comment]
@surajnarwade how should I approach it? I was thinking of creating a info.json file. Means if we don't get the flag we will load config from default location otherwise from the info.json file.

**Comment by surajnarwade** [comment]
@riteshsonawane1372 AWS SDK knows how to read from the either env or other pre-defined locations so we shouldn't be reinventing that wheel.

what I'm interested here is, cobra has functionality with which you can add global flags for example `--kubeconfig` is global flag in kubectl.

we can add `--region` in a similar way

**Comment by riteshsonawane1372** [comment]
What should be the default region for ``awsctl get ec2`` ?

**Comment by riteshsonawane1372** [comment]
![Screenshot from 2023-03-30 08-22-54](https://user-images.githubusercontent.com/72307121/228716097-f6d0b6cf-27f0-48c5-a991-5da4eb2d481c.png)

**Comment by riteshsonawane1372** [comment]
> ![Screenshot from 2023-03-30 08-22-54](https://user-images.githubusercontent.com/72307121/228716097-f6d0b6cf-27f0-48c5-a991-5da4eb2d481c.png)

Its working good, I have set the us-east-1 as the default region. Will add the --region

**Comment by riteshsonawane1372** [comment]
@surajnarwade Any other recommendation?
