### ISSUE TITLE
[FEATURE] filter resources by tags

### ISSUE THREAD

**Issue by surajnarwade** [surajincloud/awsctl#18]
### Description

Similar to kubectl where we filter resources based on labels for example,

```
kubectl get pods -l foo=bar
```

we should be able to do the same,

```
awsctl get <resource> -t foo=bar
```

here,  `-t` or `--tag` will be particular tag.

**Comment by riteshsonawane1372** [comment]
How to display the tag key and value

**Comment by riteshsonawane1372** [comment]
found this https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.DescribeTags and 

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#DescribeTagsOutput

**Comment by riteshsonawane1372** [comment]
we can have up to 49 key: value pairs, should I put them in a file? In the output section will add a column for location of tags.

**Comment by surajnarwade** [comment]
example,

Currently we have following command,

```
awsctl get ec2
```

we should be able to do,

```
awsctl get ec2 -t env=production
```

**Comment by adityasimant** [comment]
Can you assign me this issue?

**Comment by riteshsonawane1372** [comment]
> 

What if we don't know the value?, For example I want all instances with key "ritesh" and I don't know what value I have given and there exists more than one instance with same key "ritesh"

> example,
> 
> Currently we have following command,
> 
> ```
> awsctl get ec2
> ```
> 
> we should be able to do,
> 
> ```
> awsctl get ec2 -t env=production
> ```

**Comment by riteshsonawane1372** [comment]
Closing this issue #31
