### ISSUE TITLE
Request for Issue Template

### ISSUE THREAD

**Issue by adityasimant** [surajincloud/awsctl#3]
I would like to suggest creating a standardized issue template for this repository. Issue templates provide a structure for issues, making it easier for contributors to provide the necessary information.

I propose that we create a template that includes the following sections:
1. Bug report 
2. Feature request
3. Other

**Comment by riteshsonawane1372** [comment]
@surajnarwade

**Comment by riteshsonawane1372** [comment]
@adityasimant  If you are creating an Issue template then do it for pull_Request too

**Comment by adityasimant** [comment]
ok

**Comment by surajnarwade** [comment]
@adityasimant feel free to raise a PR

**Comment by surajnarwade** [comment]
closing this as we have the issue/PR template now
