### ISSUE TITLE
 Creating "Init" Subcommand

### ISSUE THREAD

**Issue by riteshsonawane1372** [surajincloud/awsctl#4]
``awsctl init``

- Creating an init cmd which will initialize a new session and ask for access key and secret.
-  Displaying a message "IAM access key and secret required not Root user. "

```   
fun sessionMain() {
  sess, err := session.NewSession(&aws.Config{
        Region: aws.String("region")},
        aws.AccessKeyID("access key"),
        aws.SecretAccessKey("secret"),
    )
}
```

**Comment by riteshsonawane1372** [comment]
The sessionMain() function will return a session and while creating any aws service we can check if the session is valid or not and if the session is not valid we can display a message "Pls run `` awsctl init``"

**Comment by riteshsonawane1372** [comment]
We can take 2 arguments access key and secret if len(args)!= 2 log.fatal ("Access key and secret required")

**Comment by surajnarwade** [comment]
we are using [aws-sdk-v2](https://github.com/aws/aws-sdk-go-v2)  so session is not needed. it automatically picks the credentials either from the env or from the config file

**Comment by riteshsonawane1372** [comment]
Sorry got confuse

**Comment by riteshsonawane1372** [comment]
Can we take argument from user and add it into $HOME/.aws/config file ?  
   We can use a bash script to create the .aws and config file
