### ISSUE TITLE
[Bug] Syntax Errors in VPC package

### ISSUE THREAD

**Issue by amalmadhu06** [surajincloud/awsctl#44]
### Description

Syntax error in the VPC package. Also, naming the package as VPC is causing `case insensitive import collision`

### Screenshots

![image](https://user-images.githubusercontent.com/46180807/233184112-d5a09e29-ea91-48f8-9f29-c85049147c96.png)

**Comment by amalmadhu06** [comment]
I'm working on this

**Comment by riteshsonawane1372** [comment]
@amalmadhu06 kindly have a look at the code https://replit.com/@riteshsonawane/FirstCyanCodec#getVPC.go

**Comment by riteshsonawane1372** [comment]
Have a look at this repo https://github.com/omsonawane1372/awsctl I ran the build and test workflow. 
![image](https://user-images.githubusercontent.com/72307121/235408777-0b98eabe-f414-47a8-be8e-0d4c0aa5549d.png)

**Comment by amalmadhu06** [comment]
Hi @riteshsonawane1372 . 
`go test ./` will only check files in the current directory. I think we need to use `go test ./...`
 I can see that `go build` is working.

I have tried to fix the syntax issues from the `vpc package`. Please see this pull request in my fork : https://github.com/amalmadhu06/awsctl/pull/1

Unfortunately, ci is again failing. Not sure what's going wrong.

**Comment by riteshsonawane1372** [comment]
> Hi @riteshsonawane1372 . `go test ./` will only check files in the current directory. I think we need to use `go test ./...` I can see that `go build` is working.
> 
> I have tried to fix the syntax issues from the `vpc package`. Please see this pull request in my fork : [amalmadhu06#1](https://github.com/amalmadhu06/awsctl/pull/1)
> 
> Unfortunately, ci is again failing. Not sure what's going wrong.

The changes in the PR won't fix the issue. Check this repo https://github.com/omsonawane1372/awsctl 
Copy the ``pkg/VPC/getVPC.go`` and ``cmd/vpc`` to ur repo

**Comment by riteshsonawane1372** [comment]
The golangci-lint will cause problems bcoz  we have mentioned ``*&x`` in some part of the code, So to run this workflow we need to change ``*&x`` to ``x``
![image](https://user-images.githubusercontent.com/72307121/235416869-d6d9c033-56ee-497a-a96c-0d082642d3da.png)

**Comment by amalmadhu06** [comment]
If possible, can you please take up this issue @riteshsonawane1372 ? I'm a bit confused here.

**Comment by riteshsonawane1372** [comment]
> If possible, can you please take up this issue @riteshsonawane1372 ? I'm a bit confused here.

Just do below changes and if it doesn't work I will work on this issue:
1.  Copy code from ``pkg/VPC/getVPC.go`` (repo :  https://github.com/omsonawane1372/awsctl) paste it in ur repo. 
2.  Copy code from `` cmd/vpc`` and paste it. 
3.  Build locally and test it, you can run ``$ make`` to build binary and run it using `` ./awsctl get vpc``

**Comment by riteshsonawane1372** [comment]
@amalmadhu06  I have open a PR ( https://github.com/surajincloud/awsctl/pull/51 ) which will solve the worflow related issue.
I ran all the workflows under https://github.com/omsonawane1372/awsctl/ Below is the result. 
![image](https://user-images.githubusercontent.com/72307121/235571613-3c807348-dd9a-475f-8ce3-87231ecbeeb3.png)

**Comment by amalmadhu06** [comment]
Thankyou @riteshsonawane1372 
Really appreciate your efforts ❤️
